services:
  db:
    image: postgres:15-alpine
    container_name: db
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      APP1_DB: ${APP1_DB}
      APP1_USER: ${APP1_USER}
      APP1_PASSWORD: ${APP1_PASSWORD}
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./init.sh:/docker-entrypoint-initdb.d/init.sh
    ports:
      - "5432:5432"  # Optional
    restart: unless-stopped

volumes:
  pgdata:
