services:
  db:
    image: postgres:15
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      APP1_USER: ${APP1_USER}              # Project-specific user
      APP1_PASSWORD: ${APP1_PASSWORD}      # Project-specific password
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./init.sh:/docker-entrypoint-initdb.d/init.sh
    ports:
      - "5432:5432"  # Optional
    restart: unless-stopped

volumes:
  pgdata:
